/* 1.0.0 VERSION */

#ifndef user_config_template_h
#define user_config_template_h

// WIFI SETTINGS
#define USER_SETTINGS_WIFI_SSID "X"
#define USER_SETTINGS_WIFI_PASSWORD "X"
#define USER_SETTINGS_WIFI_HOSTNAME "X"

// MQTT SETTINGS
#define USER_SETTINGS_MQTT_HOST "X"
#define USER_SETTINGS_MQTT_PORT 1833
#define USER_SETTINGS_MQTT_TOPIC_P "X"
#define USER_SETTINGS_MQTT_TOPIC_S "X" // not used
#define USER_SETTINGS_MQTT_DEVICE "X"
#define USER_SETTINGS_MQTT_USER "X"
#define USER_SETTINGS_MQTT_PWD "X"
#define USER_SETTINGS_MQTT_QOS 1

#endif